
# A sample of about 50 different benchmark runs, not noisy, run quickly enough,
# that appear to be somewhat diverse.

[[Benchmarks]]
  Name = "ethereum_bitutil"
  Repo = "github.com/ethereum/go-ethereum/common/bitutil"
  Tests = "Test"
  # RunWrapper = ["bar"]
  Benchmarks = "Benchmark(BaseTest2KB|FastTest2KB|Encoding4KBVerySparse)"

[[Benchmarks]]
  Name = "ethereum_storage"
  Repo = "github.com/ethereum/go-ethereum/swarm/storage"
  Tests = "Test"
  Benchmarks = "BenchmarkJoin_8" # SplitPyramid seems to have a bug
  NotSandboxed = true # Won't cross-compile to Linux on MacOS

[[Benchmarks]]
  Name = "ethereum_ethash"
  Repo = "github.com/ethereum/go-ethereum/consensus/ethash"
  Tests = "Test"
  Benchmarks = "BenchmarkHashimotoLight"
  NotSandboxed = true # Won't cross-compile to Linux on MacOS

[[Benchmarks]]
  Name = "ethereum_core"
  Repo = "github.com/ethereum/go-ethereum/core"
  Tests = "Test"
  Benchmarks = "BenchmarkChainRead_full_10k"
  NotSandboxed = true # Won't cross-compile to Linux on MacOS
  # Disabled = true # Broken as of 2018-03-05

[[Benchmarks]]
  Name = "ethereum_sha3"
  Repo = "github.com/ethereum/go-ethereum/crypto/sha3"
  Tests = "Test"
  Benchmarks = "BenchmarkSha3_224_MTU"

[[Benchmarks]]
  Name = "ethereum_ecies"
  Repo = "github.com/ethereum/go-ethereum/crypto/ecies"
  Tests = "Test"
  Benchmarks = "BenchmarkGenSharedKeyP256"
  NotSandboxed = true # Won't cross-compile to Linux on MacOS

[[Benchmarks]]
  Name = "ethereum_corevm"
  Repo = "github.com/ethereum/go-ethereum/core/vm"
  Tests = "Test"
  Benchmarks = "BenchmarkOpDiv128"
  NotSandboxed = true # Won't cross-compile to Linux on MacOS
  # Disabled = true # Broken as of 2018-04-24

[[Benchmarks]]
  Name = "ethereum_trie"
  Repo = "github.com/ethereum/go-ethereum/trie"
  Tests = "Test"
  Benchmarks = "Benchmark" # Prove and VerifyProof are noisy
  NotSandboxed = true # Won't cross-compile to Linux on MacOS
  # Disabled = true # These seem to be really noisy or tiny

[[Benchmarks]]
  Name = "ethereum_whisperv5"
  Repo = "github.com/ethereum/go-ethereum/whisper/whisperv5"
  Tests = "Test"
  Benchmarks = "Benchmark"
  # Disabled = true # These seem to be really noisy

[[Benchmarks]]
  Name = "eolian_dsp"
  Repo = "buddin.us/eolian/dsp"
  Tests = "Test"
  Benchmarks = "Benchmark"
  Disabled = true # Not always resolving host,

[[Benchmarks]]
  Name = "spexs2"
  Repo = "github.com/egonelbre/spexs2/_benchmark/"
  Tests = "Test"
  Benchmarks = "BenchmarkRun/10k/1"

[[Benchmarks]]
  Name = "minio"
  Repo = "github.com/minio/minio/cmd"
  Tests = "" # Don't run these tests; they hang, etc.
  Benchmarks = "BenchmarkGetObject5MbFS" # not Get|Put|List
  # Disabled = true # Broken as of 2018-04-24

[[Benchmarks]]
  Name = "gonum_blas_native"
  Repo = "gonum.org/v1/gonum/blas/gonum"
  Tests = "Test"
  Benchmarks = "Benchmark(DasumMediumUnitaryInc|Dnrm2MediumPosInc)" # not all benchmarks

[[Benchmarks]]
  Name = "gonum_lapack_native"
  Repo = "gonum.org/v1/gonum/lapack/gonum"
  Tests = "Test"
  Benchmarks = "BenchmarkDgeev/Circulant10"

[[Benchmarks]]
  Name = "gonum_mat"
  Repo = "gonum.org/v1/gonum/mat"
  Tests = "Test"
  Benchmarks = "Benchmark(MulWorkspaceDense1000Hundredth|ScaleVec10000Inc20)"

[[Benchmarks]]
  Name = "semver"
  Repo = "github.com/Masterminds/semver"
  Tests = "Test"
  Benchmarks = "BenchmarkValidateVersionTildeFail"

[[Benchmarks]]
  Name = "hugo_helpers"
  Repo = "github.com/gohugoio/hugo/helpers"
  Tests = "Test"
  Benchmarks = "Benchmark(StripHTML|ReaderContains)"

[[Benchmarks]]
  Name = "hugo_hugolib"
  Repo = "github.com/gohugoio/hugo/hugolib"
  Tests = "Test"
  Benchmarks = "BenchmarkParsePage"
  # Disabled = true # Broken as of 2018-04-24

[[Benchmarks]]
  Name = "hugo_hugolib_sitebuilding"
  Repo = "github.com/gohugoio/hugo/hugolib"
  Tests = "Test"
  Benchmarks = "BenchmarkSiteBuilding/YAML,num_pages=10,num_tags=10,tags_per_page=20,shortcodes,render-12" 
  # Disabled = true # Broken as of 2018-04-24

[[Benchmarks]]
  Name = "k8s_api"
  Repo = "k8s.io/kubernetes/pkg/api/testing"
  Tests = "Test"
  Benchmarks = "BenchmarkEncodeCodecFromInternalProtobuf"

[[Benchmarks]]
  Name = "k8s_schedulercache"
  Repo = "k8s.io/kubernetes/pkg/scheduler/cache"
  Tests = "Test"
  Benchmarks = "BenchmarkList1kNodes30kPods"
  # Disabled = true

[[Benchmarks]]
  Name = "uuid"
  Repo = "github.com/satori/go.uuid/"
  Tests = "Test"
  Benchmarks = "Benchmark(NewV5|MarshalToString)"

[[Benchmarks]]
  Name = "gonum_topo"
  Repo = "gonum.org/v1/gonum/graph/topo/"
  Tests = "Test"
  Benchmarks = "Benchmark(TarjanSCCGnp_1000_half|TarjanSCCGnp_10_tenth)"

[[Benchmarks]]
  Name = "gonum_path"
  Repo = "gonum.org/v1/gonum/graph/path/"
  Tests = "Test"
  Benchmarks = "Benchmark(AStarUndirectedmallWorld_10_2_2_2_Heur|Dominators/nested_if_n256)"

[[Benchmarks]]
  Name = "gonum_community"
  Repo = "gonum.org/v1/gonum/graph/community/"
  Tests = "Test"
  Benchmarks = "BenchmarkLouvainDirectedMultiplex"

[[Benchmarks]]
  Name = "gonum_traverse"
  Repo = "gonum.org/v1/gonum/graph/traverse/"
  Tests = "Test"
  Benchmarks = "BenchmarkWalkAllBreadthFirstGnp_(10|1000)_tenth" # more difference by size than anything else

[[Benchmarks]]
  Name = "capnproto2"
  Repo = "zombiezen.com/go/capnproto2/"
  Tests = "Test"
  Benchmarks = "Benchmark(TextMovementBetweenSegments|Growth_MultiSegment)"

[[Benchmarks]]
  Name = "uber_zap"
  # Repo = "github.com/uber-go/zap/benchmarks"
  Repo = "go.uber.org/zap/benchmarks"
  Tests = "Test"
  Benchmarks = "BenchmarkAddingFields/(Zap.Sugar|^[ais])"


